version: '2.1'

services:
 db:
    image: mysql:5.7
    volumes:
      - ./database/user_info.sql:/docker-entrypoint-initdb.d/user_info.sql   
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql   
      - mysql:/var/lib/msql
    restart: always  
    healthcheck: 
      test: [ "CMD", "curl", "--fail", "http://localhost:3306" ]
      interval: "60s"
      timeout: "5s"
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports: 
      - 3306:3306
 phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
 wp-cli:
    image: "wordpress:cli-php7.1"
    depends_on:
      - db
      - wordpress           
    environment:
      - APACHE_RUN_USER="www-data"
      - APACHE_RUN_GROUP="www-data"
    user: "33:33" #extremely important command. This gives permission to add the plugins
    command: >
      /bin/sh -c '
      echo "Wait 20 seconds to ensure that Wordpress is ready to be installed..";
      sleep 10;
      echo "Wordpress should be ready. Initiating account setup...";
      install;
      '
    volumes:
      - "./wordpress_data:/var/www/html"
      - "./bin/install.sh:/usr/local/bin/install:ro"
 wordpress:
   depends_on:
       db:
           condition: service_healthy
   image: wordpress:php7.1-apache
   restart: always
   ports:
      - "8000:80"
   
   environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: root
     WORDPRESS_DB_PASSWORD: password
     WORDPRESS_DB_NAME: database
   volumes:
     - "./wordpress_data:/var/www/html"   
volumes:
  mysql: {} 
  wordpress_data: {}
